# Generated by Django 4.1 on 2022-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuGiOh', '0004_alter_spellcard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapcard',
            name='image',
            field=models.ImageField(default='cards/card-back.jpg', upload_to='cards/trap_cards'),
        ),
    ]
