# Generated by Django 4.1 on 2022-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuGiOh', '0005_trapcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapcard',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Continuous', 'Continuous'), ('Counter', 'Counter'), ('Equip', 'Equip'), ('Field', 'Field')], max_length=20),
        ),
    ]
