# Generated by Django 4.1 on 2022-09-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuGiOh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boosterpackcard',
            old_name='card_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='boosterpackcard',
            old_name='card_id',
            new_name='object_id',
        ),
        migrations.AddIndex(
            model_name='boosterpackcard',
            index=models.Index(fields=['content_type', 'object_id'], name='YuGiOh_boos_content_8b7935_idx'),
        ),
    ]
