# Generated by Django 4.1 on 2022-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuGiOh', '0002_rename_card_type_boosterpackcard_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellcard',
            name='image',
            field=models.ImageField(default='cards/card-back.jpg', upload_to='cards/spell_cards'),
        ),
    ]
