# Generated by Django 4.1 on 2022-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuGiOh', '0006_alter_trapcard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstercard',
            name='image',
            field=models.ImageField(default='cards/card-back.jpg', upload_to='cards/monster_cards'),
        ),
    ]
